version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./db/.env.docker
    networks:
      - authdev
    volumes:
      - ./server:/server

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./db/.env.docker
    volumes:
      - ./db/tables.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authdev

  cronjob:
    build:
      context: ./cronjob
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - authdev
    env_file:
      - ./db/.env.docker
    volumes:
      - ./cronjob:/cronjob

networks:
  authdev:
    driver: bridge
